### ISSUE TITLE
[suggestion/feature] Slow initial loading on older/cheap phones. Fix might be hiding images?

### ISSUE THREAD

**Issue by Reinbowsaur** [ttu-ttu/ebook-reader#10]
My assumption is that images in an ebook will cause long loading times is because you always see the pictures visually loading and taking their sweet time as you are locked out until they are done loading. And, you are forced to load the pictures at a start of a book because each time the reader loads it doesn't jump straight to the bookmark, it always loads the start of the book before jumping forward.

Small QoL improvement would be adding an option to not load images at all until requested, kinda like spoiler but when clicking the spoiler the image will load there and then rather than initial loading of book. (or rather just make this the default behaviour of spoiler even)

Another way to improve performance might be to reduce the amount of pre-rendered text off screen, I'm not sure if you can control this, but I think it'd help especially slow devices.

**Comment by Renji-XD** [comment]
Had something similar in mind.

The Image Load though is more a percived Slowness i think - the major slowdown happens due to the 2nd Part you mentioned. Inserting a high amount of paragraphs / dom elements is basically taking most of the time - the dom is not performant.

Something like a virtual scroller can potentially help. Main Challenges to be solved would be the fact that most existing ones are static height dependant and most likely impacts functionality like bookmarking and character count as they are dom / scroll dependant as of today.

Lets see - i guess main focus was always desktop and mobile just came recently more in focus with jidoujisho

**Comment by ttu-ttu** [comment]
Yeah it was originally for specific users on desktop, which is why it wasn't that optimized for older devices / mobile phones.

The fix for this would be implementing virtual scroll, though I still haven't figured out the way to implement this without breaking other features

**Comment by Reinbowsaur** [comment]
Reason as to why I thought delaying loading images until requested from the book was because I've tested 2 books with and without images, and they do pretty much get about 30-40% improved speeds loading a file. Could be entirely dependant on stucture of files I'm using though? 

In the end, its not a massive issue in the slightest and it really comes down to how slow of a device you are using, was really just thinking blocking images would've being a relatively simple QoL change, now it sounds like it really comes down to effort versus reward and it doesn't seem like alot of a reward having to find some other way to improve it.

**Comment by Renji-XD** [comment]
Yah it depends on the files (how big are the source images, how many, how much text itself has it etc.).

Just to be clear: what i meant is that the majority of the load is spent on the dom itself.  Lazy Loading Images will most likely still optimize some of the load Time for slow Devices (just not the big part, and the faster the device the less you will notice it).

It seems from the theory at least easier to achieve than switching to a complete virtual scrolling element (though it adds on top complexity in case of such an implementation). I may can check the difference when i find time after the current planned story

**Comment by Renji-XD** [comment]
Yah it depends on the files (like how many images, their original size, how much text the book has etc.).

Just to be clear: What i meant is that the majority of the load resides in the dom. Still Offloading Images will most likely also lead to some lower times to a specific degree (the faster the device the less noticeable it gets).. 

Its overall easier to implement than the whole virtual scroller i guess but will already have some issues with bookmark functionality. Its currently based on the current scroll position which is problematic when it can continously change due to later or earlier loaded images. And if you want to dummy style it you would anyways need to load the images to get the width - so no benefit.

Does not hurt to keep this story as reminder for future extensions - maybe someone also finds a clever idea later

**Comment by cademcniven** [comment]
I have similar problems, but I don't have a particularly cheap phone. I also experience this in longer novels, even if there are 0 images (so I don't know that lazy loading images is the correct solution, although it should help in some cases). 

For some context, I converted a bunch of web novels to epubs because I prefer the look and feel of ttu reader, plus the character counter. One I tried to read was ~890k characters (so, longer than most LNs, but shorter than a lot of WNs). On desktop it wasn't too bad, but on mobile it was basically unusable.

The problem, like mentioned in OP, is that it doesn't load from the book mark, it sends you to the beginning of the file until it's done loading the whole thing, and the page is pretty much unresponsive until it finished (which could take several minutes in my case), and if I'm unlucky, when it finishes loading it won't jump to the bookmark so I'll have to reload and try again.

Anyways, I know you said you knew the solution already (virtual scrolling), just wanted to jump in and say there's still interest for this

**Comment by ChaseOxide** [comment]
@RawToast just FYI I'm working on page-based view (instead of continuous scroll). Internally it'll load book parts (instead of merging them into one giant html) into view, which will improve the loading time for most EPUBs

Just letting you know in case you start working on it (as mentioned in the other issue), since my changes will have a lot refactor

**Comment by ttu-ttu** [comment]
Closing this unless the pagination's not good enough for load time
