### ISSUE TITLE
[Suggestion] User Guide / Documentation

### ISSUE THREAD

**Issue by Shudouken** [ttu-ttu/ebook-reader#11]
While playing around with the web app, it took me a while to figure out that the <kbd>PageUp</kbd> and <kbd>PageDown</kbd> keys were mapped.
After finding this github page and taking a look at the source code, I saw that the <kbd>A</kbd> and <kbd>D</kbd> keys were also mapped.

Maybe there should be a built-in user guide listing all the available keyboard shortcuts or a link to the (eventual) github documentation in the settings window.
Or did you plan on making the keyboard shortcuts fully customizable?

Something simple like this should do (could also include mouse controls, mobile gestures)
| Gesture/Shortcut Key | Description |
|-------------------------|--------------|
|<kbd>Escape</kbd>|Close Panels|
|<kbd>Space</kbd>|Toggle Auto-Scrolling|
|<kbd>A</kbd>,<kbd>D</kbd>|Adjust Auto-Scrolling Speed|
|<kbd>B</kbd>|Set Bookmark|
|<kbd>PageDown</kbd>,<kbd>PageUp</kbd>|Turn Pages|
|Swipe|...|

Another minor thing, but I also noticed a general lack of tooltips.

**Comment by ttu-ttu** [comment]
I've thought of doing that, but it's actually not that simple because it's only A, D for QWERTY keyboards (as in it's mapped by key positions, not the actual alphabet). As far as I know, it's currently not possible for me to check for the keyboard layout used by the device, so it's a bit hard for me to write a user-friendly UI to show that.

Also, the auto-scrolling feature (originally) was intended to be a hidden feature, which is why A and D keys aren't implied explicitly
