### ISSUE TITLE
Reading speed stats

### ISSUE THREAD

**Issue by hopto-dot** [ttu-ttu/ebook-reader#174]
Two reading speed stats (in characters per hour) would be really helpful for tracking reading speed. These should appear next to the book progress stat at the bottom right.

### CPH if you keep reading at the same speed
Every minute, count the number of characters in between the line that was in the middle of the screen a minute ago and the line in the middle of the screen now then multiply that number by 60. Maybe this isn't a good way of doing it?

### CPH if you keep autoscrolling at the same speed
**If autoscroll is enabled**, a second stat should show that displays at what speed (in characters per hour) the screen is scrolling. This could either be done by counting exactly how many characters that will appear in the next minute then multiplying by 60, or, using a constant that is different for every novel based on average number of characters you would scroll in an hour.
I like the latter here because you'd be able to use it to make better estimations about the whole book in calculations.

**Comment by Renji-XD** [comment]
point 1 is i think kind of part #6 (just not mentioned that extensivly). though i would simply do it based on the existing character count/progress meaning right screen for vertical, top screen for horizontal. anchor point shouldn't matter as there will never be a good representation of how someone will read the text in the continous mode and any kind of scrolling will anyways update the counter.

point 2 i don't really get the difference / benefit to 1.. if your speed is x/h it does not really matter if its because you scrolled manually or because the autoscroll moved the content. maybe higher / more accurate but if you are able to keep up then simply take this value as granted? (especially as it is anyways kind of fuzzy value like all stats)

**Comment by therealgrumpythomas** [comment]
I made a tiny [userscript](https://greasyfork.org/en/scripts/459921-reading-speed-statistics-ttsu-app)  which adds the following information beneath the existing characters. Got positive feedback from the moe way community so maybe you could take the following into consideration:
![Screenshot_20230212_164001_Kiwi_Browser](https://user-images.githubusercontent.com/125606560/219883280-bc4041b3-477c-4f48-83aa-c55c27198764.jpg)

These statistics answer the following questions:

- how long did I read?
- how many characters did I read?
- how fast did I read?
