### ISSUE TITLE
[Feature] Ability to select multiple Files or a Directory

### ISSUE THREAD

**Issue by Renji-XD** [ttu-ttu/ebook-reader#2]
As an User i want to be able to select multiple Files at once or a Directory for which recursively all Files are added.

Navigation / last Item can remain the same (meaning update it to the last item in the list and stored in db)

Single Click => One File, Double Click => Directory

Not sure how many People will actually use it but the effort / implication on the app seems relative low (and could also be useful for testing other stuff like book manager etc.)

**Comment by wizo06** [comment]
As far as I'm aware of, the design philosophy of *ttu-ebook* is to be a simple and lightweight ebook reader, not an ebook manager.

**Comment by Renji-XD** [comment]
Would potentially take it as chance to start looking a bit into the code and to make #4 a bit easier in case i'll try that too.

@ttu-ttu what is better - new folder icon or single / double click/tap on the icon / dropzone via delayed event listener on existing file icon?

Would start as described with navigating to the last succesfull loaded book. In Context of #4 the manage view could potentially be shown to choose which book to load later on

**Comment by ttu-ttu** [comment]
Think should just reuse the existing icon and make it accept multiple files, same for the drag and drop

**Comment by Renji-XD** [comment]
ya thats clear - i was refering to a directory selection. Adding it will enforce a folder selection and only fallbacks to files if the browser does not support it. Therefore that would be a separate input which gets triggered.

So first decision is if you only want to allow a file selection (which can only be in the same one directory) or also directories (e. g. to add multiple series from a root folder at once or whatever).
 
And if directories will be allowed a decision how the user can choose between a file and a directory selection. And for that i guess it could be either a new icon for the reader and/or an overloaded single/double click handler on the existing file icon (which would be anyways required at least for the dropzone as there are no icons)

**Comment by wizo06** [comment]
I second the decision of using a separate icon for "import folder". This will allow existing users and new users to infer that they can import a single file or an entire folder.

Before we move forward though, there are a few points that I would like to bring up:

- If the user imports an entire folder, what will happen to unsupported files?
- Change the icon for "import folder" to [this](https://fontawesome.com/v5.15/icons/folder-upload?style=solid). (I know that the books aren't being uploaded to anywhere and they're stored locally. But that was the only folder icon which resembles some sort of "import")
- To make things consistent, also change the icon for "file import" to [this](https://fontawesome.com/v5.15/icons/file-upload?style=solid), so that they both have the arrow pointing up.
- The progress bar in your screenshots looks fine to me. Although i'm not sure how i feel about the color.
- The alert that pops up in your second screenshot has two buttons: "Upload" and "Cancel". Would it be possible to change the word "Upload" to "Import" instead?

**Comment by Renji-XD** [comment]
> If the user imports an entire folder, what will happen to unsupported files?
Same as of now - the File is will be skipped and if there not at least one supported File was found the alert is shown

> The progress bar in your screenshots looks fine to me. Although i'm not sure how i feel about the color.
Its just like a default for me because dark bg and green color reminds me of matrix : > . If you have any preference let me know. I think we can use a static (theme independant) value as the bg color will make most of the background not visible anyways

> Would it be possible to change the word "Upload" to "Import" instead?
Not that i am aware of - it comes from native Browser Dialogs which are typically never changeable unfortunately.

Will then for now use the icons you mentioned (+ double click on the dropzone where no icons exist) and add directory support until i hear something else.

**Comment by wizo06** [comment]
I like the `file-medical` and `folder-plus` icons. 

Would it be possible to change the progress bar from that striped green to a solid green?

**Comment by Renji-XD** [comment]
> striped green to a solid green?

You mean removing the animation => https://imgur.com/a/aRLzWkf ?

**Comment by wizo06** [comment]
Yes. Looks better.

Now we just need @ttu-ttu 's approval.

**Comment by ttu-ttu** [comment]
Resolved in #8
