### ISSUE TITLE
cannot find "Add URI" when follow steps inside section "Storage Sources"

### ISSUE THREAD

**Issue by joanmj** [ttu-ttu/ebook-reader#237]
>If you develop locally or self host the reader click on "Add URI" inside the "Single-page Application" box and add "http://localhost:5173/auth" and/or adjust ports etc. depending on your needs;

I try to create a custom credentials but failed when follow the steps, need help pls;

And I notice that, when i visit "http://localhost:5173/auth" on my self host site, it seems error happened, turn out a page "403 Forbidden
nginx/1.23.3" as the  result; it cannot access, maybe because i didn't set any Environment Variables, is it right?

**Comment by joanmj** [comment]
hope soon webdav could be a option for sync; maybe more useful than hard to create a custom credential.....

**Comment by Renji-XD** [comment]
hi,
it should look like this for you:
![image](https://github.com/ttu-ttu/ebook-reader/assets/6409827/a835daac-55a3-452c-93ce-a2ec05d888a9)

(also tested with a new registered app so you should theoretically get to this screen too)

regarding your selfhost: not sure as i don't know your config.. but it sounds like your server is trying to serve the directory instead of the html.. i just noticed sth similiar seems to be the case for the one in the provided docker image.. i just pushed a fix which at least seems to work on my end.. maybe you can compare your config with the one in the repo (in the apps/web/nginx/conf.d directory)? 

let me know if your issues were solved

**Comment by Renji-XD** [comment]
Closing for now - feel free to reopen this one in case you still have questions
