### ISSUE TITLE
Can't upload .epubs to ttu reader

### ISSUE THREAD

**Issue by tensigh** [ttu-ttu/ebook-reader#323]
Every time I try to get an .epub into ttu-reader it fails. 

Does anyone know how to get good copies of .epubs? I can't download them from amazon.co.jp and the online ones don't work.

**Comment by Renji-XD** [comment]
Hi,

my assumption is you are probably trying to upload drm protected files which the reader is unable to process. I am not aware of any major (or actually even a single) bookstores not selling files without drm. If you need to support to remove this / how to download from stores i would suggest to look for further support in communities like refold or TheMoeWay - they typically have resources which describes these processess (and have people to answer questions)

As i don't see this in scope of this app / no open point i'll close this issue. Feel free though to share a link or attach an example of an file - if i find it is related to a site bug i will reopen this issue but otherwise checkout the communities i suggested
