### ISSUE TITLE
[Feature Request] Image zoom

### ISSUE THREAD

**Issue by khaitruong922** [ttu-ttu/ebook-reader#368]
Some images have text which are too small to read without zooming in. Due to how the website layout works, the image will not be zoomed even though we adjust the zoom of the page.

On mobile, it is not possible to open image in new tab or pinch to zoom the page.

On desktop, when open image on new tab, it will show the blob format instead of the image.
![image](https://github.com/user-attachments/assets/9508f239-2745-47f8-981a-92b89de9a556)

Would be nice to be able to open the image in new tab, or have some ways to view the image zoomed within the page.

**Comment by khaitruong922** [comment]
Looks like this only happens for epub files stored in Drive as it does not store the image in local storage or indexeddb.

**Comment by Renji-XD** [comment]
closed by #370 

it should work for most cases right away, for some exceptions you may need to reload the epub file.

Opening the (unspoilered) image is now possible via holding down mouse/pointer on the image for 1 sec (required on mobile) and/or context menu where available

**Comment by khaitruong922** [comment]
I don't think the problem is in the epub file but how the images are stored when loading epub within Drive. Can you try to reproduce it and let me know the behavior?

**Comment by Renji-XD** [comment]
this is not what i meant.

the broken images should be in general fixed by the pr i referenced in my previous comment and be applied after couple of tab refreshes - i just wrote it may can help to reload the file in case you still encounter some exceptions as the rootcause was due to missing mimetypes.. so it could be that there was corrupted data uploaded by the reader

**Comment by khaitruong922** [comment]
it works now, thanks for the fix!
